# 📦 넘파이 ndarray 객체 생성하기

In [1]:
import numpy as np

모든 넘파이 배열의 타입은 ndarray 객체다

## TIP) 차원 이해하기
- 어떤 배열의 shape이 (n, m)이라 가정해보자.
- 이때 바깥 차원의 숫자부터 읽어야 한다. 다음과 같은 흐름을 이해해야 한다.
    1. n개의 ndarray 객체가 있네?
    2. 각 ndarray 객체는 총 m개가 있네?

## 1) 파이썬 리스트로 배열 만들기

In [2]:
# 벡터
vec_py = [1, 2, 3]
vec_np = np.array(vec_py)

print(vec_np)
print(vec_np.shape)
print(type(vec_np))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [3]:
# 행렬
mat_py = [[1, 2, 3],
          [4, 5, 6]]
mat_np = np.array(mat_py)

print(mat_np)
print(mat_np.shape)
print(type(mat_np))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [4]:
# 3차원
tensor_py = [[[1, 2, 3],
             [4, 5, 6]],
            
             [[7, 8, 9],
             [10, 11, 12]]]
tensor_np = np.array(tensor_py)

print(tensor_np)
print(tensor_np.shape)
print(type(tensor_np))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
<class 'numpy.ndarray'>


## 2) 특정 shape의 배열 만들기

### np.zeros

In [5]:
# M = np.zeros(shape=(2, 3))
M = np.zeros((2, 3))
print(M)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones

In [7]:
# M = np.ones(shape=(2, 3))
M = np.ones((2, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]]


### np.full

In [8]:
# M = np.full(shape=(2, 3), fill_value=7)
M = np.full((2, 3), 7)
print(M)

[[7 7 7]
 [7 7 7]]


### np.empty
특정 값으로 초기화 하는 것이 아니라 위치(공간)만 잡아놓고 값은 나중에 채운다.

In [9]:
# N = np.empty(shape=(2, 3))
N = np.empty((2, 3))
print(N)

[[1. 1. 1.]
 [1. 1. 1.]]


## 3) 정해진 간격과 개수의 배열 만들기

### np.arange
- 처음은 포함하지만 마지막은 포함하지 않는다.
- 구간, 간격에 중점을 둔다.

In [10]:
print(np.arange(10))
print(np.arange(2, 5))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4 6 8]


In [11]:
# 실수 입력 가능
print(np.arange(10.5))
print(np.arange(1.5, 10.5))
print(np.arange(1.5, 10.5, 2.5))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
[1.5 4.  6.5 9. ]


### np.linspace
- 처음과 마지막을 포함한다.
- 개수에 중점을 둔다.

In [12]:
print(np.linspace(0, 1, 5))
print(np.linspace(0, 1, 10))

[0.   0.25 0.5  0.75 1.  ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
print(np.linspace([1, 10, 100], [2, 20, 200], 5))

[[  1.    10.   100.  ]
 [  1.25  12.5  125.  ]
 [  1.5   15.   150.  ]
 [  1.75  17.5  175.  ]
 [  2.    20.   200.  ]]


## 4) 랜덤 배열 만들기

### 정규분포
1. np.random.randn (표준정규분포)
2. np.random.normal
    - loc (평균), scale(표준편차)

In [14]:
# np.random.randn(300)

In [15]:
# np.random.normal(
#     loc=-2,
#     scale=1,
#     size=(100, )
# )

In [16]:
# np.random.normal(
#     loc=[-2, 0, 3],
#     scale=[1, 2, 5],
#     size=(200, 3)
# )

### 균일분포
1. np.random.rand
    - [0, 1)
2. np.random.uniform
3. np.random.randint
    - 처음은 포함 O, 마지막은 포함 X

In [17]:
# np.random.rand

# print(np.random.rand(10))
# print('================================================')
# print(np.random.rand(2, 3, 4))

In [18]:
# np.random.uniform

# np.random.uniform(
#     low=-10,
#     high=10,
#     size=(5, )
# )

In [19]:
# # np.random.randint
# np.random.randint(
#     low=0,
#     high=10,
#     size=(5, )
# )