# 🔮 넘파이 ndarray 객체 수정하기
ndarray 객체 모양 바꾸기

In [1]:
import numpy as np

## 1) np.reshape
ndarray.reshape

In [2]:
a = np.arange(6)
b = np.reshape(a, (2, 3))

print('original ndarray: \n', a)
print('reshaped ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]


In [3]:
a = np.arange(24)
b = np.reshape(a, (2, 3, 4))

print('original ndarray: \n', a)
print('reshaped ndarray: \n', b)

original ndarray: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
# ndarray.reshape
a = np.arange(6)
b = a.reshape((2, 3))

print('original ndarray: \n', a)
print('reshaped ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]


In [5]:
# 가독성 보장
a = np.random.randint(0, 100, (100, ))
a.reshape((20, 5)).mean(axis=0).max()

58.5

### -1 인수로 전달하기
자동으로 나머지 차원의 길이를 계산한다.

In [6]:
a = np.arange(12)

print('first ndarray:\n', a.reshape(2, -1))
print('second ndarray:\n', a.reshape(3, -1))
print('third ndarray:\n', a.reshape(4, -1))

first ndarray:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
second ndarray:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
third ndarray:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
# 3차원
a = np.arange(24)
print(a.reshape(2, 3, -1).shape)
print(a.reshape(2, 6, -1).shape)

(2, 3, 4)
(2, 6, 2)


In [8]:
a = np.random.randint(0, 10, size=(2, 2))
print('a ndarray:')
print(a)

# 행 벡터
row_vec = a.reshape(1, -1)
print('row_vec ndarray:')
print(row_vec)
print(row_vec.shape)

# 열 벡터
col_vec = a.reshape(-1, 1)
print('col_vec ndarray:')
print(col_vec)
print(col_vec.shape)

a ndarray:
[[4 6]
 [6 2]]
row_vec ndarray:
[[4 6 6 2]]
(1, 4)
col_vec ndarray:
[[4]
 [6]
 [6]
 [2]]
(4, 1)


## 2) np.resize
- 원소의 개수를 바꾼다. 부족분은 반복해서 추가한다.
- ndarray.resize (inplace)

In [9]:
a = np.arange(6)
b = np.resize(a, (2, 3))

print('original ndarray: \n', a)
print('resized ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5]
resized ndarray: 
 [[0 1 2]
 [3 4 5]]


In [10]:
a = np.arange(6)
b = np.resize(a, (9, ))

print('original ndarray: \n', a)
print('resized ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5]
resized ndarray: 
 [0 1 2 3 4 5 0 1 2]


In [11]:
a = np.arange(9)
b = np.resize(a, (2, 2))

print('original ndarray: \n', a)
print('resized ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5 6 7 8]
resized ndarray: 
 [[0 1]
 [2 3]]


In [12]:
# 2차원
a = np.arange(6)
b = np.resize(a, (3, 4))

print('original ndarray: \n', a)
print('resized ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5]
resized ndarray: 
 [[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]


In [13]:
# 3차원
a = np.arange(9)
b = np.resize(a, (2, 3, 3))

print('original ndarray: \n', a)
print('resized ndarray: \n', b)

original ndarray: 
 [0 1 2 3 4 5 6 7 8]
resized ndarray: 
 [[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [14]:
# ndarray.resize 메서드는 inplace 특징을 갖는다. (리턴값 존재 X)
a = np.arange(9)
b = a.resize((2, 2))

print('original ndarray: \n', a)
print('resized ndarray1: \n', b)

# ndarray.resize 메서드는 다음과 같이 사용한다.
c = np.arange(9)
c.resize((3, 2))

print('resized ndarray2: \n', c)

original ndarray: 
 [[0 1]
 [2 3]]
resized ndarray1: 
 None
resized ndarray2: 
 [[0 1]
 [2 3]
 [4 5]]


## 3) ndarray.flatten
- 벡터를 생성한다.
- np.reshape(ndarray.reshape) 메서드의 역연산
- flatten 순서에 유의

In [15]:
M = np.arange(9)
N = M.reshape((3, 3))
O = N.flatten()

print('M is as follows:\n', M)
print('N is as follows:\n', N)
print('O is as follows:\n', O)

M is as follows:
 [0 1 2 3 4 5 6 7 8]
N is as follows:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
O is as follows:
 [0 1 2 3 4 5 6 7 8]


In [16]:
# 3차원
M = np.arange(27)
N = M.reshape((3, 3, 3))
O = N.flatten()

print('M is as follows:\n', M)
print('N is as follows:\n', N)
print('O is as follows:\n', O)

M is as follows:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
N is as follows:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
O is as follows:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


## 4) ndarray.ravel
벡터를 생성한다.

In [17]:
M = np.arange(9)
N = M.reshape((3, 3))
O = N.ravel()

print('M is as follows:\n', M)
print('N is as follows:\n', N)
print('O is as follows:\n', O)

M is as follows:
 [0 1 2 3 4 5 6 7 8]
N is as follows:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
O is as follows:
 [0 1 2 3 4 5 6 7 8]


## 5) Copy & View
- Copy: 원본 객체에 영향을 미치면 안되는 경우에 사용한다.
- View: 원본 객체에 영향을 미쳐도 상관이 없는 경우에 사용한다.
    - 메모리 낭비를 방지하기 위해 View 방식을 사용한다.

In [18]:
# 넘파이 배열의 슬라이싱은 View
a = np.arange(5)
b = a[:3]

b[...] = 10
print('a :\n', a)
print('b :\n', b)

a :
 [10 10 10  3  4]
b :
 [10 10 10]


In [19]:
a = np.arange(5)
b = a.copy()
c = a.view()
d = a[:3]

print(b.base is a)
print(c.base is a)
print(d.base is a)

False
True
True


In [20]:
# reshape 메서드 (View)
a = np.arange(4)
b = np.reshape(a, (2, 2))

b[0, 0] = 100
print(b.base is a)
print('a:\n', a)
print('b:\n', b)

True
a:
 [100   1   2   3]
b:
 [[100   1]
 [  2   3]]


In [21]:
a = np.arange(4)
b = np.reshape(a, (2, 2)).copy()

b[0, 0] = 100

print(b.base is a)
print('a:\n', a)
print('b:\n', b)

False
a:
 [0 1 2 3]
b:
 [[100   1]
 [  2   3]]


In [22]:
# resize 메서드 (Copy)
a = np.arange(5)
b = np.resize(a, (2, 2))

b[0, 0] = 100
print(b.base is a)
print('a:\n', a)
print('b:\n', b)

False
a:
 [0 1 2 3 4]
b:
 [[100   1]
 [  2   3]]


In [23]:
# flatten 메서드 (Copy)
a = np.random.randint(0, 10, (2, 3))
b = a.flatten()
b[0] = -999

print(b.base is a)
print('a:\n', a)
print('b:\n', b)

False
a:
 [[1 2 0]
 [4 2 5]]
b:
 [-999    2    0    4    2    5]


In [24]:
# ravel 메서드 (View)
a = np.random.randint(0, 10, (2, 3))
b = a.ravel()
b[0] = -999

print(b.base is a)
print('a:\n', a)
print('b:\n', b)

True
a:
 [[-999    9    8]
 [   5    4    9]]
b:
 [-999    9    8    5    4    9]


## 6) ndarray.astype
텐서플로우는 float32 타입이 기본형이다.

In [25]:
M = np.array([1, 2, 3], np.int8)
N = M.astype(np.uint32)
O = M.astype(np.float32)

print('M dtype:\n', M.dtype)
print('N dtype:\n', N.dtype)
print('O dtype:\n', O.dtype)

M dtype:
 int8
N dtype:
 uint32
O dtype:
 float32


In [26]:
# 숫자와 불리언 비교
print(-3 == True, -3 == False)
print(3.12 == True, 3.14 == False)

print(0. == True, 0. == False)
print(1. == True, 1. == False)

False False
False False
False True
True False
