# 넘파이 배열의 (반)올림/내림, 정렬

In [1]:
import numpy as np

## ✅ 라운딩
- 데이터를 보기 좋게 출력할 때 주로 사용한다.
- 연산 중에는 라운딩 보다는 truncate을 더 자주 사용한다.

### np.around, np.round_, ndarray.round

In [48]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

np_around = np.around(x, decimals=2)
print('\n소수점 둘째 자리까지 반올림:', np_around)

np_round = np.round_(x, decimals=2)
print('소수점 둘째 자리까지 반올림:', np_round)

x_round = x.round(decimals=2)
print('소수점 둘째 자리까지 반올림:', x_round)

x = [-4.63448893 -3.6640049  -4.20992863  0.4298574  -0.14902338]

소수점 둘째 자리까지 반올림: [-4.63 -3.66 -4.21  0.43 -0.15]
소수점 둘째 자리까지 반올림: [-4.63 -3.66 -4.21  0.43 -0.15]
소수점 둘째 자리까지 반올림: [-4.63 -3.66 -4.21  0.43 -0.15]


In [49]:
scores = np.random.uniform(0, 100, (100, 5))

means = scores.mean(axis=0)
stds = scores.std(axis=0)
print('평균(axis=0):', means)
print('표준편차(axis=0):', stds)

print('\n평균(axis=0) 소수점 둘째 자리까지 반올림:', means.round(2))
print('표준편차(axis=0) 소수점 둘째 자리까지 반올림:', stds.round(2))

평균(axis=0): [49.71435182 51.26917625 51.75912014 55.57267783 53.1721001 ]
표준편차(axis=0): [27.73390949 28.01932176 28.29724233 26.74518404 29.17900363]

평균(axis=0) 소수점 둘째 자리까지 반올림: [49.71 51.27 51.76 55.57 53.17]
표준편차(axis=0) 소수점 둘째 자리까지 반올림: [27.73 28.02 28.3  26.75 29.18]


### np.ceil, np.floor

In [50]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

ceil = np.ceil(x)
floor = np.floor(x)
print('\n올림:', ceil)
print('내림:', floor)

x = [-2.00884357  1.8069884  -4.58606967 -0.92602145 -1.79827853]

올림: [-2.  2. -4. -0. -1.]
내림: [-3.  1. -5. -1. -2.]


### np.trunc

In [51]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc = np.trunc(x)
print('\n절삭:', trunc)

x = [-2.68853157  0.3005923  -3.21555829 -3.88809331  0.94475056]

절삭: [-2.  0. -3. -3.  0.]


In [53]:
# ceil, floor
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc_where = np.where(x >= 0, np.floor(x), np.ceil(x))
print('\nnp.where 메서드를 사용한 절삭:', trunc_where)

x = [-0.53942239 -0.18512171 -1.06627938 -1.38833356  1.82261277]

np.where 메서드를 사용한 절삭: [-0. -0. -1. -1.  1.]


In [54]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc = 0.1 * np.trunc(10*x)
print('\n소수점 첫째 자리까지만 남긴 결과:', trunc)

trunc2 = 0.01 * np.trunc(100*x)
print('소수점 둘째 자리까지만 남긴 결과:', trunc2)

x = [ 4.42522737 -1.87759473 -0.46330662  2.76970045 -4.80316838]

소수점 첫째 자리까지만 남긴 결과: [ 4.4 -1.8 -0.4  2.7 -4.8]
소수점 둘째 자리까지만 남긴 결과: [ 4.42 -1.87 -0.46  2.76 -4.8 ]


In [8]:
# 정수와 소수 분리
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

int_part = np.trunc(x)
frac_part = x - int_part

print('\n정수 부분: ', int_part)
print('소수 부분: ', frac_part)

x = [ 3.89831561  1.8492261   2.14956895  1.97091291 -3.45363415]

정수 부분:  [ 3.  1.  2.  1. -3.]
소수 부분:  [ 0.89831561  0.8492261   0.14956895  0.97091291 -0.45363415]


## ✅ 정렬
- 2가지 정렬 방식
    1. 데이터에 대한 정렬 방식 (np.sort)
    2. 인덱스에 대한 정렬 방식 (np.argsort)
        - (정렬된 배열 원소의) 기존 배열에서의 인덱스

### 1차원 (벡터)

In [ ]:
# 디폴트는 오름차순
x = np.random.randint(0, 100, (10, ))
print('x =', x)

sort = np.sort(x)
print('\n오름차순 정렬:', sort)

argsort = np.argsort(x)
print('오름차순 정렬(argsort):', argsort)

print('argsort를 사용해서 정렬한 결과:', x[argsort])

In [61]:
x = np.random.randint(0, 100, (10, ))
print('x =', x)

sort = np.sort(x)[::-1]
print('\n내림차순 정렬:', sort)

x = [ 9 72 34 90 17  0 53 74 18 78]

내림차순 정렬: [90 78 74 72 53 34 18 17  9  0]


In [21]:
# 예시
pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()
print('pred:\n', pred)

top3_pred = np.sort(pred)[::-1][:3]
print('\ntop3_pred:\n', top3_pred)

top3_indices = np.argsort(pred)[::-1][:3]
print('top3_indices:\n', top3_indices)

print('top3 is as follows:', pred[top3_indices])

pred:
 [0.31853593 0.01149958 0.17995092 0.31467816 0.1753354 ]

top3_pred:
 [0.31853593 0.31467816 0.17995092]
top3_indices:
 [0 3 2]
top3 is as follows: [0.31853593 0.31467816 0.17995092]


### 2차원 (행렬)

In [62]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort = np.sort(x, axis=0)
print('\n오름차순 정렬(axis=0):\n', sort)

argsort = np.argsort(x, axis=0)
print('오름차순 정렬(axis=0; argsort):\n', argsort)

x =
 [[56  2 32 83 87]
 [84 89 66 51 26]
 [81  6 39 69 22]
 [51 40 99 32 53]]

오름차순 정렬(axis=0):
 [[51  2 32 32 22]
 [56  6 39 51 26]
 [81 40 66 69 53]
 [84 89 99 83 87]]
오름차순 정렬(axis=0; argsort):
 [[3 0 0 3 2]
 [0 2 2 1 1]
 [2 3 1 2 3]
 [1 1 3 0 0]]


In [63]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort = np.sort(x, axis=0)[::-1, :]
print('\n내림차순 정렬(axis=0):\n', sort)

argsort = np.argsort(x, axis=0)[::-1, :]
print('내림차순 정렬(axis=0; argsort):\n', argsort)

x =
 [[87 65  7 40 12]
 [22 10 84  2 34]
 [90 20 11 24 87]
 [19 57 29 76 31]]

내림차순 정렬(axis=0):
 [[90 65 84 76 87]
 [87 57 29 40 34]
 [22 20 11 24 31]
 [19 10  7  2 12]]
내림차순 정렬(axis=0; argsort):
 [[2 0 1 3 2]
 [0 3 3 0 1]
 [1 2 2 2 3]
 [3 1 0 1 0]]


In [70]:
# 예시 (과목 3개별 학생 5명의 시험 점수)
scores = np.random.randint(0, 100, (5, 3))
print('점수표 =\n', scores)

sort = np.sort(scores, axis=0)[::-1, :]
print('\n내림차순 정렬(axis=0):\n', sort)

argsort = np.argsort(scores, axis=0)[::-1, :]
print('내림차순 정렬(axis=0; argsort):\n', argsort)

top2_scores = sort[:2, :]
print('\n과목별 높은 점수:\n', top2_scores)
top2_scores_idx = argsort[:2, :]
print('과목별 높은 점수를 받은 학생(인덱스):\n', top2_scores_idx)

점수표 =
 [[42  0 26]
 [85 32  1]
 [24 39 53]
 [61 84 76]
 [ 3  0 47]]

내림차순 정렬(axis=0):
 [[85 84 76]
 [61 39 53]
 [42 32 47]
 [24  0 26]
 [ 3  0  1]]
내림차순 정렬(axis=0; argsort):
 [[1 3 3]
 [3 2 2]
 [0 1 4]
 [2 4 0]
 [4 0 1]]

과목별 높은 점수:
 [[85 84 76]
 [61 39 53]]
과목별 높은 점수를 받은 학생(인덱스):
 [[1 3 3]
 [3 2 2]]


In [68]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort_ascending = np.sort(x, axis=1)
print('\n오름차순 정렬(axis=1):\n', sort_ascending)
argsort_ascending = np.argsort(x, axis=1)
print('오름차순 정렬(axis=1; argsort):\n', argsort_ascending)

sort_descending = np.sort(x, axis=1)[:, ::-1]
print('\n내림차순 정렬(axis=1):\n', sort_descending)
argsort_descending = np.argsort(x, axis=1)[:, ::-1]
print('내림차순 정렬(axis=1; argsort):\n', argsort_descending)

x =
 [[54 58 17 91 77]
 [41 48 57  1 45]
 [65 27 17 22 25]
 [ 8 51 68 72 66]]

오름차순 정렬(axis=1):
 [[17 54 58 77 91]
 [ 1 41 45 48 57]
 [17 22 25 27 65]
 [ 8 51 66 68 72]]
오름차순 정렬(axis=1; argsort):
 [[2 0 1 4 3]
 [3 0 4 1 2]
 [2 3 4 1 0]
 [0 1 4 2 3]]

내림차순 정렬(axis=1):
 [[91 77 58 54 17]
 [57 48 45 41  1]
 [65 27 25 22 17]
 [72 68 66 51  8]]
내림차순 정렬(axis=1; argsort):
 [[3 4 1 0 2]
 [2 1 4 0 3]
 [0 1 4 3 2]
 [3 2 4 1 0]]


In [72]:
# 예시 (과목 3개별 학생 5명의 시험 점수)
scores = np.random.randint(0, 100, (5, 3))
print('점수표 =\n', scores)

sort = np.sort(scores, axis=1)
print('\n오름차순 정렬(axis=1):\n', sort)

argsort = np.argsort(scores, axis=1)
print('오름차순 정렬(axis=1; argsort):\n', argsort)

lowest_2subjects_per_stud = sort[:, :2]
print('\n학생별 가장 시험을 못 본 두 과목의 점수:\n', lowest_2subjects_per_stud)

lowest_2subjects_per_stud_idx = argsort[:, :2]
print('학생별 시험을 가장 못 본 두 과목(인덱스):\n', lowest_2subjects_per_stud_idx)

점수표 =
 [[67 75 73]
 [61 89 95]
 [93 79 14]
 [99 90 86]
 [ 6 36 80]]

오름차순 정렬(axis=1):
 [[67 73 75]
 [61 89 95]
 [14 79 93]
 [86 90 99]
 [ 6 36 80]]
오름차순 정렬(axis=1; argsort):
 [[0 2 1]
 [0 1 2]
 [2 1 0]
 [2 1 0]
 [0 1 2]]

학생별 가장 시험을 못 본 두 과목의 점수:
 [[67 73]
 [61 89]
 [14 79]
 [86 90]
 [ 6 36]]
학생별 시험을 가장 못 본 두 과목(인덱스):
 [[0 2]
 [0 1]
 [2 1]
 [2 1]
 [0 1]]
