# ✂️ 넘파이 ndarray 객체 합곱차, 통계값

In [1]:
import numpy as np

## ✅ 합곱차

### cumsum
텐서의 연산 보다는 시각화할 때 주로 사용

In [2]:
a = np.arange(5)
print('a =', a)

cumsum = np.cumsum(a)
print('np.cumsum(a) =', cumsum)

a = [0 1 2 3 4]
np.cumsum(a) = [ 0  1  3  6 10]


In [3]:
a = np.arange(9).reshape((3, 3))
print('a =\n', a)

cumsum = np.cumsum(a)
print('\nnp.cumsum(a) =', cumsum)
print('shape =', cumsum.shape)

a =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

np.cumsum(a) = [ 0  1  3  6 10 15 21 28 36]
shape = (9,)


In [4]:
a = np.arange(12).reshape((3, -1))
print('a =\n', a)

cumsum = np.cumsum(a, axis=0)
print('\nnp.cumsum(a, axis=0) =\n', cumsum)
print('shape =', cumsum.shape)

a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.cumsum(a, axis=0) =
 [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
shape = (3, 4)


In [5]:
a = np.arange(12).reshape((3, -1))
print('a =\n', a)

cumsum = np.cumsum(a, axis=1)
print('\nnp.cumsum(a, axis=1) =\n', cumsum)
print('shape =', cumsum.shape)

a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.cumsum(a, axis=1) =
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
shape = (3, 4)


---

In [6]:
a = np.arange(2*3*4).reshape((2, 3, 4))
print('a =', a)
print('\nnp.cumsum(a)[::-1] =\n', np.cumsum(a)[::-1])

a = [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

np.cumsum(a)[::-1] =
 [276 253 231 210 190 171 153 136 120 105  91  78  66  55  45  36  28  21
  15  10   6   3   1   0]


In [7]:
a = np.arange(12).reshape((3, -1))
print('a =\n', a)

cumsum = np.cumsum(a, axis=0)[::-1, :]
print('\nnp.cumsum(a, axis=0)[::-1, :] =\n', cumsum)
print('shape =', cumsum.shape)

a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.cumsum(a, axis=0)[::-1, :] =
 [[12 15 18 21]
 [ 4  6  8 10]
 [ 0  1  2  3]]
shape = (3, 4)


In [8]:
a = np.arange(12).reshape((3, -1))
print('a =\n', a)

cumsum = np.cumsum(a, axis=1)[:, ::-1]
print('\nnp.cumsum(a, axis=1)[:, ::-1] =\n', cumsum)
print('shape =', cumsum.shape)

a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.cumsum(a, axis=1)[:, ::-1] =
 [[ 6  3  1  0]
 [22 15  9  4]
 [38 27 17  8]]
shape = (3, 4)


### prod, cumprod

In [9]:
a = np.arange(1, 5)
print('a =', a)

prod = np.prod(a)
print('np.prod(a) =', prod)

cumprod = np.cumprod(a)
print('np.cumprod(a) =', cumprod)

a = [1 2 3 4]
np.prod(a) = 24
np.cumprod(a) = [ 1  2  6 24]


In [10]:
a = np.arange(1, 5)
print('a =', a)

prod = np.prod(a)
print('np.prod(a) =', prod)

cumprod = np.cumprod(a)[::-1]
print('np.cumprod(a)[::-1] =', cumprod)

a = [1 2 3 4]
np.prod(a) = 24
np.cumprod(a)[::-1] = [24  6  2  1]


In [11]:
a = np.arange(1, 13).reshape((3, 4))
print('a =\n', a)

prod = np.prod(a, axis=0)
print('\nnp.prod(a, axis=0) =\n', prod)

cumprod = np.cumprod(a, axis=0)
print('\nnp.cumprod(a, axis=0) =\n', cumprod)

a =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.prod(a, axis=0) =
 [ 45 120 231 384]

np.cumprod(a, axis=0) =
 [[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]


### diff
- 길이가 하나 감소한다.
- 미분식에서 사용 → f(n+1) - f(n)

In [12]:
a = np.random.randint(0, 10, (5, ))
print('a =', a)

diff = np.diff(a)
print('np.diff(a) =', diff)

a = [4 1 5 7 2]
np.diff(a) = [-3  4  2 -5]


In [13]:
# 행이 하나 감소
a = np.random.randint(0, 10, (4, 4))
print('a =\n', a)

diff = np.diff(a, axis=0)
print('\nnp.diff(a, axis=0) =\n', diff)

a =
 [[2 1 0 5]
 [5 7 8 6]
 [2 6 2 7]
 [9 6 9 9]]

np.diff(a, axis=0) =
 [[ 3  6  8  1]
 [-3 -1 -6  1]
 [ 7  0  7  2]]


In [14]:
# 열이 하나 감소
a = np.random.randint(0, 10, (4, 4))
print('a =\n', a)

diff = np.diff(a, axis=1)
print('\nnp.diff(a, axis=1) =\n', diff)

a =
 [[7 4 2 3]
 [3 0 3 6]
 [1 4 7 7]
 [6 3 0 3]]

np.diff(a, axis=1) =
 [[-3 -2  1]
 [-3  3  3]
 [ 3  3  0]
 [-3 -3  3]]


## ✅ 통계값

### mean
평균의 사용 빈도는 높다.

In [15]:
a = np.random.randint(0, 5, (3, 4))
print('a =\n', a)

mean = np.mean(a)
print('np.mean(a) =', mean)

mean2 = np.mean(a, axis=0)
print('np.mean(a, axis=0) =\n', mean2)

mean3 = np.mean(a, axis=1)
print('np.mean(a, axis=1) =\n', mean3)

a =
 [[1 1 2 0]
 [0 1 1 1]
 [2 3 3 3]]
np.mean(a) = 1.5
np.mean(a, axis=0) =
 [1.         1.66666667 2.         1.33333333]
np.mean(a, axis=1) =
 [1.   0.75 2.75]


### median

In [16]:
# 홀수
x = np.arange(9)
print('x =', x)

median = np.median(x)
print('np.median(x) =', median)

x = [0 1 2 3 4 5 6 7 8]
np.median(x) = 4.0


In [17]:
# 짝수
x = np.arange(10)
print('x =', x)

median = np.median(x)
print('np.median(x) =', median)

x = [0 1 2 3 4 5 6 7 8 9]
np.median(x) = 4.5


### var, std
표준편차(std)의 사용 빈도는 높다.

In [18]:
scores = np.random.normal(
    loc=10,
    scale=5,
    size=(100, )
)

var = scores.var()
std = scores.std()

print('var =', var)
print('std =', std)

var = 19.493118867167944
std = 4.415101229549323


### 표준화

In [19]:
means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3

scores = np.random.normal(
    loc=means,
    scale=stds,
    size=(n_student, n_class)
)
scores = scores.astype(np.float32)

means = scores.mean(axis=0)
stds = scores.std(axis=0)

print('평균 before 표준화 =', means)
print('표준편차 before 표준화 =', stds)

scores_std = (scores - means) / stds

means_std = scores_std.mean(axis=0)
stds_std = scores_std.std(axis=0)

print('\n평균 after 표준화 =', means_std)
print('표준편차 after 표준화 =', stds_std)


평균 before 표준화 = [50.680626 60.45018  71.18604 ]
표준편차 before 표준화 = [2.8257637 5.1551867 9.249413 ]

평균 after 표준화 = [ 1.718998e-06 -5.352497e-07 -7.176399e-07]
표준편차 after 표준화 = [1. 1. 1.]
