# 넘파이 배열의 (반)올림/내림, 정렬

In [1]:
import numpy as np

## ✅ 라운딩
- 데이터를 보기 좋게 출력할 때 주로 사용한다.
- 연산 중에는 라운딩 보다는 truncate을 더 자주 사용한다.

### np.around, np.round_, ndarray.round

In [2]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

np_around = np.around(x, decimals=2)
print('\n소수점 둘째 자리까지 반올림:', np_around)

np_round = np.round_(x, decimals=2)
print('소수점 둘째 자리까지 반올림:', np_round)

x_round = x.round(decimals=2)
print('소수점 둘째 자리까지 반올림:', x_round)

x = [ 4.08062482 -1.02134143  1.14181548  4.84734524  0.56987377]

소수점 둘째 자리까지 반올림: [ 4.08 -1.02  1.14  4.85  0.57]
소수점 둘째 자리까지 반올림: [ 4.08 -1.02  1.14  4.85  0.57]
소수점 둘째 자리까지 반올림: [ 4.08 -1.02  1.14  4.85  0.57]


In [3]:
scores = np.random.uniform(0, 100, (100, 5))

means = scores.mean(axis=0)
stds = scores.std(axis=0)
print('평균(axis=0):', means)
print('표준편차(axis=0):', stds)

print('\n평균(axis=0) 소수점 둘째 자리까지 반올림:', means.round(2))
print('표준편차(axis=0) 소수점 둘째 자리까지 반올림:', stds.round(2))

평균(axis=0): [50.07310455 50.66182387 49.86773246 52.2244294  43.17491559]
표준편차(axis=0): [28.3292946  28.41898148 28.30939764 26.89909115 27.47645741]

평균(axis=0) 소수점 둘째 자리까지 반올림: [50.07 50.66 49.87 52.22 43.17]
표준편차(axis=0) 소수점 둘째 자리까지 반올림: [28.33 28.42 28.31 26.9  27.48]


### np.ceil, np.floor

In [4]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

ceil = np.ceil(x)
floor = np.floor(x)
print('\n올림:', ceil)
print('내림:', floor)

x = [2.00651103 4.98124618 3.81190872 4.61711096 0.12876648]

올림: [3. 5. 4. 5. 1.]
내림: [2. 4. 3. 4. 0.]


### np.trunc

In [5]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc = np.trunc(x)
print('\n절삭:', trunc)

x = [ 3.09862613  1.72348063  3.77810802 -0.65354404  0.70847888]

절삭: [ 3.  1.  3. -0.  0.]


In [6]:
# ceil, floor
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc_where = np.where(x >= 0, np.floor(x), np.ceil(x))
print('\nnp.where 메서드를 사용한 절삭:', trunc_where)

x = [-2.88671556 -3.04863403  3.82191026 -2.4257358  -4.74153067]

np.where 메서드를 사용한 절삭: [-2. -3.  3. -2. -4.]


In [7]:
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

trunc = 0.1 * np.trunc(10*x)
print('\n소수점 첫째 자리까지만 남긴 결과:', trunc)

trunc2 = 0.01 * np.trunc(100*x)
print('소수점 둘째 자리까지만 남긴 결과:', trunc2)

x = [-2.97713745 -1.99431795 -4.49209765 -0.02043337 -1.10261682]

소수점 첫째 자리까지만 남긴 결과: [-2.9 -1.9 -4.4 -0.  -1.1]
소수점 둘째 자리까지만 남긴 결과: [-2.97 -1.99 -4.49 -0.02 -1.1 ]


In [8]:
# 정수와 소수 분리
x = np.random.uniform(-5, 5, (5, ))
print('x =', x)

int_part = np.trunc(x)
frac_part = x - int_part

print('\n정수 부분: ', int_part)
print('소수 부분: ', frac_part)

x = [4.45705915 1.000912   1.42414618 3.19642889 0.18029428]

정수 부분:  [4. 1. 1. 3. 0.]
소수 부분:  [0.45705915 0.000912   0.42414618 0.19642889 0.18029428]


## ✅ 정렬
- 2가지 정렬 방식
    1. 데이터에 대한 정렬 방식 (np.sort)
    2. 인덱스에 대한 정렬 방식 (np.argsort)
        - (정렬된 배열 원소의) 기존 배열에서의 인덱스

### 1차원 (벡터)

In [9]:
# 디폴트는 오름차순
x = np.random.randint(0, 100, (10, ))
print('x =', x)

sort = np.sort(x)
print('\n오름차순 정렬:', sort)

argsort = np.argsort(x)
print('오름차순 정렬(argsort):', argsort)

print('argsort를 사용해서 정렬한 결과:', x[argsort])

x = [49 94 77 85  1 96 27 26 41 82]

오름차순 정렬: [ 1 26 27 41 49 77 82 85 94 96]
오름차순 정렬(argsort): [4 7 6 8 0 2 9 3 1 5]
argsort를 사용해서 정렬한 결과: [ 1 26 27 41 49 77 82 85 94 96]


In [10]:
x = np.random.randint(0, 100, (10, ))
print('x =', x)

sort = np.sort(x)[::-1]
print('\n내림차순 정렬:', sort)

x = [67 15 46 58 21 62 57 21 36 21]

내림차순 정렬: [67 62 58 57 46 36 21 21 21 15]


In [11]:
# 예시
pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()
print('pred:\n', pred)

top3_pred = np.sort(pred)[::-1][:3]
print('\ntop3_pred:\n', top3_pred)

top3_indices = np.argsort(pred)[::-1][:3]
print('top3_indices:\n', top3_indices)

print('top3 is as follows:', pred[top3_indices])

pred:
 [0.23913355 0.34796672 0.32047448 0.01673948 0.07568576]

top3_pred:
 [0.34796672 0.32047448 0.23913355]
top3_indices:
 [1 2 0]
top3 is as follows: [0.34796672 0.32047448 0.23913355]


### 2차원 (행렬)

In [12]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort = np.sort(x, axis=0)
print('\n오름차순 정렬(axis=0):\n', sort)

argsort = np.argsort(x, axis=0)
print('오름차순 정렬(axis=0; argsort):\n', argsort)

x =
 [[51 17 69 76 21]
 [ 0 92 60 59 21]
 [62 73 44  4 12]
 [87 77  5 40 99]]

오름차순 정렬(axis=0):
 [[ 0 17  5  4 12]
 [51 73 44 40 21]
 [62 77 60 59 21]
 [87 92 69 76 99]]
오름차순 정렬(axis=0; argsort):
 [[1 0 3 2 2]
 [0 2 2 3 0]
 [2 3 1 1 1]
 [3 1 0 0 3]]


In [13]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort = np.sort(x, axis=0)[::-1, :]
print('\n내림차순 정렬(axis=0):\n', sort)

argsort = np.argsort(x, axis=0)[::-1, :]
print('내림차순 정렬(axis=0; argsort):\n', argsort)

x =
 [[56 38 57 99 41]
 [28 56 35 47  5]
 [46 78 86 47 67]
 [42 28  8  0 15]]

내림차순 정렬(axis=0):
 [[56 78 86 99 67]
 [46 56 57 47 41]
 [42 38 35 47 15]
 [28 28  8  0  5]]
내림차순 정렬(axis=0; argsort):
 [[0 2 2 0 2]
 [2 1 0 2 0]
 [3 0 1 1 3]
 [1 3 3 3 1]]


In [14]:
# 예시 (과목 3개별 학생 5명의 시험 점수)
scores = np.random.randint(0, 100, (5, 3))
print('점수표 =\n', scores)

sort = np.sort(scores, axis=0)[::-1, :]
print('\n내림차순 정렬(axis=0):\n', sort)

argsort = np.argsort(scores, axis=0)[::-1, :]
print('내림차순 정렬(axis=0; argsort):\n', argsort)

top2_scores = sort[:2, :]
print('\n과목별 높은 점수:\n', top2_scores)
top2_scores_idx = argsort[:2, :]
print('과목별 높은 점수를 받은 학생(인덱스):\n', top2_scores_idx)

점수표 =
 [[63 93 10]
 [42 36 24]
 [33 35 98]
 [48 87 13]
 [75 16  0]]

내림차순 정렬(axis=0):
 [[75 93 98]
 [63 87 24]
 [48 36 13]
 [42 35 10]
 [33 16  0]]
내림차순 정렬(axis=0; argsort):
 [[4 0 2]
 [0 3 1]
 [3 1 3]
 [1 2 0]
 [2 4 4]]

과목별 높은 점수:
 [[75 93 98]
 [63 87 24]]
과목별 높은 점수를 받은 학생(인덱스):
 [[4 0 2]
 [0 3 1]]


In [15]:
x = np.random.randint(0, 100, (4, 5))
print('x =\n', x)

sort_ascending = np.sort(x, axis=1)
print('\n오름차순 정렬(axis=1):\n', sort_ascending)
argsort_ascending = np.argsort(x, axis=1)
print('오름차순 정렬(axis=1; argsort):\n', argsort_ascending)

sort_descending = np.sort(x, axis=1)[:, ::-1]
print('\n내림차순 정렬(axis=1):\n', sort_descending)
argsort_descending = np.argsort(x, axis=1)[:, ::-1]
print('내림차순 정렬(axis=1; argsort):\n', argsort_descending)

x =
 [[38 17 20 66  7]
 [57 99 81  7 74]
 [19 22 76 28 27]
 [80 26 42 30 99]]

오름차순 정렬(axis=1):
 [[ 7 17 20 38 66]
 [ 7 57 74 81 99]
 [19 22 27 28 76]
 [26 30 42 80 99]]
오름차순 정렬(axis=1; argsort):
 [[4 1 2 0 3]
 [3 0 4 2 1]
 [0 1 4 3 2]
 [1 3 2 0 4]]

내림차순 정렬(axis=1):
 [[66 38 20 17  7]
 [99 81 74 57  7]
 [76 28 27 22 19]
 [99 80 42 30 26]]
내림차순 정렬(axis=1; argsort):
 [[3 0 2 1 4]
 [1 2 4 0 3]
 [2 3 4 1 0]
 [4 0 2 3 1]]


In [16]:
# 예시 (과목 3개별 학생 5명의 시험 점수)
scores = np.random.randint(0, 100, (5, 3))
print('점수표 =\n', scores)

sort = np.sort(scores, axis=1)
print('\n오름차순 정렬(axis=1):\n', sort)

argsort = np.argsort(scores, axis=1)
print('오름차순 정렬(axis=1; argsort):\n', argsort)

lowest_2subjects_per_stud = sort[:, :2]
print('\n학생별 가장 시험을 못 본 두 과목의 점수:\n', lowest_2subjects_per_stud)

lowest_2subjects_per_stud_idx = argsort[:, :2]
print('학생별 시험을 가장 못 본 두 과목(인덱스):\n', lowest_2subjects_per_stud_idx)

점수표 =
 [[72 84 15]
 [72 90 38]
 [99 83 73]
 [ 5 58 21]
 [98  3 81]]

오름차순 정렬(axis=1):
 [[15 72 84]
 [38 72 90]
 [73 83 99]
 [ 5 21 58]
 [ 3 81 98]]
오름차순 정렬(axis=1; argsort):
 [[2 0 1]
 [2 0 1]
 [2 1 0]
 [0 2 1]
 [1 2 0]]

학생별 가장 시험을 못 본 두 과목의 점수:
 [[15 72]
 [38 72]
 [73 83]
 [ 5 21]
 [ 3 81]]
학생별 시험을 가장 못 본 두 과목(인덱스):
 [[2 0]
 [2 0]
 [2 1]
 [0 2]
 [1 2]]
