# 넘파이 배열 반복하기
반복문을 대체할 수 있다.

In [1]:
import numpy as np

## ✅ np.repeat
- np.repeat(a, repeats, axis)
- 원소별 반복(각 원소를 지정한 횟수만큼 반복)

In [2]:
# 스칼라
x = 3

rep = np.repeat(x, 2)
print('np.repeat(3, 2): ', rep)

np.repeat(3, 2):  [3 3]


In [3]:
# 벡터
x = np.array([1, 2, 3])

rep = np.repeat(x, 3)
print('np.repeat([1, 2, 3], 3): ', rep)

np.repeat([1, 2, 3], 3):  [1 1 1 2 2 2 3 3 3]


In [12]:
# 행렬
x = np.arange(4).reshape((2, 2))
print('x =\n', x)

rep_noaxis = np.repeat(x, 3)
print('\nrep_noaxis,', '{}:\n'.format(rep_noaxis.shape), rep_noaxis)

rep_axis0 = np.repeat(x, 3, axis=0)
print('\nrep_axis0,', '{}:\n'.format(rep_axis0.shape), rep_axis0)

rep_axis1 = np.repeat(x, 3, axis=1)
print('\nrep_axis1,', '{}:\n'.format(rep_axis1.shape), rep_axis1)

x =
 [[0 1]
 [2 3]]

rep_noaxis, (12,):
 [0 0 0 1 1 1 2 2 2 3 3 3]

rep_axis0, (6, 2):
 [[0 1]
 [0 1]
 [0 1]
 [2 3]
 [2 3]
 [2 3]]

rep_axis1, (2, 6):
 [[0 0 0 1 1 1]
 [2 2 2 3 3 3]]


In [13]:
# repeats 매개변수에 리스트를 전달
x = np.arange(4).reshape((2, 2))
print('x =\n', x)

# 첫번째 원소는 2번, 두번째 원소는 1번 반복
rep = np.repeat(x, repeats=[2, 1], axis=0)
print('\nrep,', '{}:\n'.format(rep.shape), rep)

x =
 [[0 1]
 [2 3]]

rep, (3, 2):
 [[0 1]
 [0 1]
 [2 3]]


In [14]:
x = np.arange(6).reshape((2, 3))
print('x =\n', x)

rep = np.repeat(x, repeats=[2, 1, 2], axis=1)
print('\nrep,', '{}:\n'.format(rep.shape), rep)

x =
 [[0 1 2]
 [3 4 5]]

rep, (2, 5):
 [[0 0 1 2 2]
 [3 3 4 5 5]]


In [15]:
# 행벡터 반복
row_vec = np.arange(4).reshape((1, -1))
print('row_vec =\n', row_vec)

rep = np.repeat(row_vec, 3, axis=0)
print('\nrep,', '{}:\n'.format(rep.shape), rep)

row_vec =
 [[0 1 2 3]]

rep, (3, 4):
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [16]:
# 열벡터 반복
col_vec = np.arange(4).reshape((-1, 1))
print('col_vec =\n', col_vec)

rep = np.repeat(col_vec, 3, axis=1)
print('\nrep,', '{}:\n'.format(rep.shape), rep)

col_vec =
 [[0]
 [1]
 [2]
 [3]]

rep, (4, 3):
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


## ✅ np.tile
- np.tile(a, reps)
- 전체를 반복(배열 자체를 반복)
- 2차원 배열(행렬)을 다룰 때 자주 사용한다.

In [18]:
a = np.arange(4)
print('a =', a)

tile = np.tile(a, 3)
print('\ntile,', '{}:\n'.format(tile.shape), tile)

a = [0 1 2 3]

tile, (12,):
 [0 1 2 3 0 1 2 3 0 1 2 3]


In [22]:
a = np.arange(3)
print('a =', a)

tile1 = np.tile(a, reps=[1, 2])
print('\ntile1,', '{}:\n'.format(tile1.shape), tile1)

tile2 = np.tile(a, reps=[2, 1])
print('\ntile2,', '{}:\n'.format(tile2.shape), tile2)

# 행 방향으로 2번, 열 방향으로 2번 반복
tile3 = np.tile(a, reps=[2, 2])
print('\ntile3,', '{}:\n'.format(tile3.shape), tile3)

a = [0 1 2]

tile1, (1, 6):
 [[0 1 2 0 1 2]]

tile2, (2, 3):
 [[0 1 2]
 [0 1 2]]

tile3, (2, 6):
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [27]:
# 행렬
a = np.arange(6).reshape((2, 3))
print('a,', '{}:\n'.format(a.shape),a)

# 행 방향으로 1번, 열 방향으로 2번 반복
tile = np.tile(a, reps=[1, 2])
print('\ntile,', '{}:\n'.format(tile.shape), tile)

# 행 방향으로 2번, 열 방향으로 1번 반복
tile2 = np.tile(a, reps=[2, 1])
print('\ntile2,', '{}:\n'.format(tile2.shape), tile2)

# 행 방향으로 2번, 열 방향으로 2번 반복
tile3 = np.tile(a, reps=[2, 2])
print('\ntile3,', '{}:\n'.format(tile3.shape), tile3)

a, (2, 3):
 [[0 1 2]
 [3 4 5]]

tile, (2, 6):
 [[0 1 2 0 1 2]
 [3 4 5 3 4 5]]

tile2, (4, 3):
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]

tile3, (4, 6):
 [[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [34]:
a = np.arange(6).reshape((2, 3))
print('a,', '{}:\n'.format(a.shape), a)

reps = np.array([3, 5])
tile = np.tile(a, reps=reps)
print('\ntile,', '{}:\n'.format(tile.shape), tile)
print('& reps * a.shape =', reps * a.shape)

a, (2, 3):
 [[0 1 2]
 [3 4 5]]

tile, (6, 15):
 [[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5 3 4 5 3 4 5]]
& reps * a.shape = [ 6 15]


In [40]:
# 행벡터
a = np.arange(4).reshape((1, -1))
print('a,', '{}:\n'.format(a.shape), a)

tile = np.tile(a, reps=[5, 1])
print('\ntile,', '{}:\n'.format(tile.shape), tile)

a, (1, 4):
 [[0 1 2 3]]

tile, (5, 4):
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [41]:
# 열벡터
a = np.arange(4).reshape((-1, 1))
print('a,', '{}:\n'.format(a.shape), a)

tile = np.tile(a, reps=[1, 5])
print('\ntile,', '{}:\n'.format(tile.shape), tile)

a, (4, 1):
 [[0]
 [1]
 [2]
 [3]]

tile, (4, 5):
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
