# 넘파이 배열의 인덱싱과 슬라이싱

In [1]:
import numpy as np

## ✅ 1차원
- 파이썬 리스트와 같이 반복문 사용이 가능하다.

### 인덱싱
파이썬 리스트 인덱싱 외에도 추가 기능을 제공한다.

In [2]:
a = np.arange(10)
print('a =', a)

print('a[0] =', a[0])
print('a[3] =', a[3])

print('a[-1] =', a[-1])
print('a[-3] =', a[-3])

a = [0 1 2 3 4 5 6 7 8 9]
a[0] = 0
a[3] = 3
a[-1] = 9
a[-3] = 7


In [3]:
# 추가 기능 1
a = np.arange(10)
indices = np.array([0, 3, 6, -1])
print('a =', a)

print('a[[0, 3, 6, -1]] =', a[[0, 3, 6, -1]])
print('a[indices] =', a[indices])
print('a[a % 3 == 0] =', a[a % 3 == 0])

a = [0 1 2 3 4 5 6 7 8 9]
a[[0, 3, 6, -1]] = [0 3 6 9]
a[indices] = [0 3 6 9]
a[a % 3 == 0] = [0 3 6 9]


In [4]:
# 추가 기능 2 (for문 대체) ⭐️⭐️⭐️⭐️⭐️
a = np.arange(1, 11)
print('a =', a)

a[:5] = 0
print('a =', a)

b = np.arange(1, 11)
print('b =', b)

b[::2] = 999
print('b =', b)

a = [ 1  2  3  4  5  6  7  8  9 10]
a = [ 0  0  0  0  0  6  7  8  9 10]
b = [ 1  2  3  4  5  6  7  8  9 10]
b = [999   2 999   4 999   6 999   8 999  10]


### 슬라이싱
- arr[x, y)

In [5]:
a =np.arange(10)
print('a =', a)

print('a[0:3] =', a[0:3])
print('a[5:-1] =', a[5:-1])
print('a[-2:] =', a[-2:])  # last 2 elements

print('a[::3] =', a[::3])
print('a[7:2:-1] =', a[7:2:-1])
print('a[::-1] =', a[::-1])

a = [0 1 2 3 4 5 6 7 8 9]
a[0:3] = [0 1 2]
a[5:-1] = [5 6 7 8]
a[-2:] = [8 9]
a[::3] = [0 3 6 9]
a[7:2:-1] = [7 6 5 4 3]
a[::-1] = [9 8 7 6 5 4 3 2 1 0]


## ✅ 2차원
- 바깥쪽 차원(outer dimension)부터 접근한다.
- 서로 다른 차원은 콤마를 기준으로 인덱싱한다.

In [6]:
a = np.arange(12).reshape((3, 4))
print('a=\n', a)

print('a[0] =', a[0])
print('a[2] =', a[2])

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0] = [0 1 2 3]
a[2] = [ 8  9 10 11]


In [7]:
a = np.arange(9).reshape((3, 3))
print('a=\n', a)

print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
print(a[2, 0], a[2, 1], a[2, 2])

a=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
0 1 2
3 4 5
6 7 8


In [8]:
a = np.arange(12).reshape((4, 3))
print('a:\n', a)

print('a[0, 1:]=\n', a[0, 1:])
print('a[1:, 0]=\n', a[1:, 0])
print('a[:3, 1]=\n', a[:3, 1])
print('a[1:3, 2]=\n', a[1:3, 2])

a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a[0, 1:]=
 [1 2]
a[1:, 0]=
 [3 6 9]
a[:3, 1]=
 [1 4 7]
a[1:3, 2]=
 [5 8]


In [9]:
a = np.arange(16).reshape((4, 4))
print('a:\n', a)

print('a[1:3, 1:3]=\n', a[1:3, 1:3])
print('a[:2, :-1]=\n', a[:2, :-1])
print('a[1:, -2:]\n', a[1:, -2:])
print('a[-2:, :-2]\n', a[-2:, :-2])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a[1:3, 1:3]=
 [[ 5  6]
 [ 9 10]]
a[:2, :-1]=
 [[0 1 2]
 [4 5 6]]
a[1:, -2:]
 [[ 6  7]
 [10 11]
 [14 15]]
a[-2:, :-2]
 [[ 8  9]
 [12 13]]


In [10]:
a = np.arange(9).reshape((3, 3))
print('a:\n', a)

horizontal_flip = a[:, ::-1]
print('horizontal_flip:\n', horizontal_flip)

vertical_flip = a[::-1, :]
print('vertical_flip:\n', vertical_flip)

rotation180 = a[::-1, ::-1]
print('rotation180\n:', rotation180)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
horizontal_flip:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
vertical_flip:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
rotation180
: [[8 7 6]
 [5 4 3]
 [2 1 0]]


In [11]:
# ... 기호의 의미
a = np.arange(16).reshape((4, 4))
print('a:\n', a)

print('a[0, :]:\n', a[0, :])
print('a[0, ...]:\n', a[0, ...])

print('a[:, 1]:\n', a[:, 1])
print('a[..., 1]:\n', a[..., 1])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a[0, :]:
 [0 1 2 3]
a[0, ...]:
 [0 1 2 3]
a[:, 1]:
 [ 1  5  9 13]
a[..., 1]:
 [ 1  5  9 13]


## ✅ 3차원
바깥 차원에서부터 접근한다.

In [12]:
a = np.arange(27).reshape((3, 3, 3))
print('a:\n', a)

print('a[0] =\n', a[0])
print('a[1] =\n', a[1])
print('a[2] =\n', a[2])

a:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
a[0] =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a[1] =
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
a[2] =
 [[18 19 20]
 [21 22 23]
 [24 25 26]]


In [13]:
a = np.arange(27).reshape((3, 3, 3))
print('a:\n', a)

print('a[0, 0] =\n', a[0, 0])
print('a[0, 1] =\n', a[0, 1])
print('a[0, 2] =\n', a[0, 2])

print('a[1, 0] =\n', a[1, 0])
print('a[1, 1] =\n', a[1, 1])
print('a[1, 2] =\n', a[1, 2])

print('a[2, 0] =\n', a[2, 0])
print('a[2, 1] =\n', a[2, 1])
print('a[2, 2] =\n', a[2, 2])

a:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
a[0, 0] =
 [0 1 2]
a[0, 1] =
 [3 4 5]
a[0, 2] =
 [6 7 8]
a[1, 0] =
 [ 9 10 11]
a[1, 1] =
 [12 13 14]
a[1, 2] =
 [15 16 17]
a[2, 0] =
 [18 19 20]
a[2, 1] =
 [21 22 23]
a[2, 2] =
 [24 25 26]


In [14]:
a = np.arange(27).reshape((3, 3, 3))
print('a:\n', a)

print('a[0, :-1, :-1] =\n', a[0, :-1, :-1])
print('a[1, :-1, :] =\n', a[1, :-1, :])
print('a[2, 1:, 1:] =\n', a[2, 1:, 1:])

a:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
a[0, :-1, :-1] =
 [[0 1]
 [3 4]]
a[1, :-1, :] =
 [[ 9 10 11]
 [12 13 14]]
a[2, 1:, 1:] =
 [[22 23]
 [25 26]]


In [15]:
images = np.random.normal(size=(32, 100, 200))

print('image0:\n', images[0, :, :].shape)
print('image0:\n', images[0, ...].shape)

print('col0:\n', images[:, :, 0].shape)
print('col0:\n', images[..., 0].shape)

print('image0_col0:\n', images[0, :, 0].shape)
print('image0_col0:\n', images[0, ..., 0].shape)

image0:
 (100, 200)
image0:
 (100, 200)
col0:
 (32, 100)
col0:
 (32, 100)
image0_col0:
 (100,)
image0_col0:
 (100,)


In [16]:
a = np.arange(27).reshape((3, 3, 3))

print('a[:, -1, :] =\n', a[:, :-1, :])
print('a[..., 0] =\n', a[..., 0])
print('a[1:, 1:, 1:] =\n', a[1:, 1:, 1:])

a[:, -1, :] =
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
a[..., 0] =
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
a[1:, 1:, 1:] =
 [[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [17]:
image = np.random.normal(size=(3, 500, 300))
image_r = image[0]
image_g = image[1]
image_b = image[2]
print(image_r.shape, image_g.shape, image_b.shape)

image2 = np.random.normal(size=(500, 300, 3))
image2_r = image2[..., 0]
image2_g = image2[..., 1]
image2_b = image2[..., 2]
print(image2_r.shape, image2_g.shape, image2_b.shape)

(500, 300) (500, 300) (500, 300)
(500, 300) (500, 300) (500, 300)


In [18]:
image = np.random.normal(size=(3, 500, 300))
image_r, image_g, image_b = image
print(image_r.shape, image_b.shape, image_b.shape)

(500, 300) (500, 300) (500, 300)


In [19]:
image = np.random.normal(size=(3, 500, 300))

top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]
print(top_left.shape, top_right.shape, bottom_left.shape, bottom_right.shape)

(3, 100, 100) (3, 100, 100) (3, 100, 100) (3, 100, 100)


## ✅ 인덱싱(정수 배열)
정수 배열의 shape은 인덱싱 결과 배열의 shape에 영향을 미친다.

In [20]:
a = np.arange(9)
print('a:\n', a)

indices = [0, 3, 4]
print('a[indices] =', a[indices])

a:
 [0 1 2 3 4 5 6 7 8]
a[indices] = [0 3 4]


In [21]:
a = np.arange(10)
print('a:\n', a)

indices = [0, 0, 5, 5, 8]
print('a[indices] =', a[indices])

a:
 [0 1 2 3 4 5 6 7 8 9]
a[indices] = [0 0 5 5 8]


In [22]:
# 1차원
a = np.arange(10)
print('a:\n', a)

indices = np.array([[1, 2, 3], [5, 8, 9]])
print('a[indices] =\n', a[indices])

a:
 [0 1 2 3 4 5 6 7 8 9]
a[indices] =
 [[1 2 3]
 [5 8 9]]


In [23]:
# 1차원
a = np.random.randint(0, 20, (10, ))
print('a:\n', a)

indices = np.random.randint(0, 10, size=(2, 3, 4))
print('a[indices] =\n', a[indices])

a:
 [ 4 19  6  8 18  4 17  8  0  1]
a[indices] =
 [[[ 4  4  0  6]
  [ 4  6  8  6]
  [ 6  4  4 19]]

 [[19  0 18  4]
  [ 4  4 19  4]
  [ 6  0  1 17]]]


In [24]:
# 2차원
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

# 2개를 인덱싱하고 싶은데 각각의 크기가 (4, ) → 최종 shape은 (2, 4)
indices = np.array([0, 2])
print('a[indices] =\n', a[indices])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[indices] =
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [25]:
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

# 6개를 인덱싱하고 싶은데 각각의 크기가 (4, ) → 최종 shape은 (6, 4)
indices = np.array([0, 0, 1, 1, 2, 2])
print('a[indices] =\n', a[indices])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[indices] =
 [[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]


In [26]:
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

indices = np.array([[0, 1, 2], [-3, -2, -1]])  # shape: (2, 3)
print('a[indices] =\n', a[indices])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[indices] =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [27]:
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

print('a[0, 0] =', a[0, 0])

indices0, indices1 = np.array([0]), np.array([0])
print('a[indices, indices1] =', a[indices0, indices1])

indices2, indices3 = np.array([1]), np.array([2])
print('a[indices2, indices3] =', a[indices2, indices3])

indices4, indices5 = np.array([-1]), np.array([0])
print('a[indices4, indices5] =', a[indices4, indices5])

indices6, indices7 = np.array([-1]), np.array([-1])
print('a[indices6, indices7] =', a[indices6, indices7])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0, 0] = 0
a[indices, indices1] = [0]
a[indices2, indices3] = [6]
a[indices4, indices5] = [8]
a[indices6, indices7] = [11]


### 💡 정수(인덱스) 배열이 2개

In [28]:
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

indices0, indices1 = np.array([0, 1, 2]), np.array([1, 2, 3])  # shape (3, )
print('a[indices0, indices1] =\n', a[indices0, indices1])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[indices0, indices1] =
 [ 1  6 11]


In [29]:
a = np.arange(12).reshape((3, 4))
print('a:\n', a)

# shape (2, 3)
indices0 = np.array([[0, 1, 2], [0, 1, 2]])
indices1 = np.array([[0, 1, 2], [1, 2, 3]])

print('a[indices0, indices1] =\n', a[indices0, indices1])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[indices0, indices1] =
 [[ 0  5 10]
 [ 1  6 11]]


## ✅ 인덱싱(불리언 배열)
인덱싱 대상 배열과 shape이 동일해야 한다.

In [30]:
a = np.arange(5)
print('a:\n', a)

b_indices = np.array([True, False, True, False, True])
print('a[b_indices] =', a[b_indices])

a:
 [0 1 2 3 4]
a[b_indices] = [0 2 4]


In [31]:
a = np.random.randint(0, 20, (10, ))
print('a:\n', a)

b_indices = (a % 2 == 0)
print('b_indices =', b_indices)
print('a[b_indices] =', a[b_indices])

a:
 [15  8  9 13 10  1  2  7 14  8]
b_indices = [False  True False False  True False  True False  True  True]
a[b_indices] = [ 8 10  2 14  8]


In [32]:
a = np.random.randint(0, 20, (2, 2))
print('a:\n', a)

b_indices = np.array([[True, False],
                     [False, True]])

print('a[b_indices] =\n', a[b_indices])

a:
 [[ 7  8]
 [ 2 14]]
a[b_indices] =
 [ 7 14]


In [33]:
a = np.random.randint(0, 20, (2, 2))
print('a:\n', a)

b_indices = (a > 10)
print('a[b_indices] =\n', a[b_indices])

a:
 [[14  5]
 [19 15]]
a[b_indices] =
 [14 19 15]


### np.nonzero, np.where
정수 배열을 리턴하기 때문에 이 두 API의 결과를 사용해 인덱싱이 가능하다.

In [34]:
a = np.array([True, False, True, False])

nonzero = np.nonzero(a)
where = np.where(a)

print('nonzero =', nonzero)
print('where =', where)

nonzero = (array([0, 2]),)
where = (array([0, 2]),)


In [35]:
a = np.array([[True, False], [True, False]])

nonzero = np.nonzero(a)
where = np.where(a)

print('nonzero =', nonzero, '→', '(0, 0) & (1, 0)')
print('where =', where, '→', '(0, 0) & (1, 0)')

nonzero = (array([0, 1]), array([0, 0])) → (0, 0) & (1, 0)
where = (array([0, 1]), array([0, 0])) → (0, 0) & (1, 0)


In [36]:
a = np.array([[[True, False, True],
              [True, False, False]],
             [[False, True, False],
             [True, False, True]]])
print('a:\n', a)

nonzero = np.nonzero(a)
where = np.where(a)

print('nonzero =', nonzero, '\n', '→', '(0, 0, 0) & (0, 0, 2) & ...')
print('where =', where, '\n', '→', '(0, 0, 0) & (0, 0, 2) & ...')

a:
 [[[ True False  True]
  [ True False False]]

 [[False  True False]
  [ True False  True]]]
nonzero = (array([0, 0, 0, 1, 1, 1]), array([0, 0, 1, 0, 1, 1]), array([0, 2, 0, 1, 0, 2])) 
 → (0, 0, 0) & (0, 0, 2) & ...
where = (array([0, 0, 0, 1, 1, 1]), array([0, 0, 1, 0, 1, 1]), array([0, 2, 0, 1, 0, 2])) 
 → (0, 0, 0) & (0, 0, 2) & ...


In [37]:
a = np.random.randint(-2, 3, size=(3, 3))
print('a:\n', a)

# 형태가 arr[indices0, indices1]와 동일
u_nonzero = a[np.nonzero(a)]  # 정수 배열
u_where = a[np.where(a)]  # 정수 배열
u_bool = a[a != 0]  # 불리언 배열

print('u_nonzero =\n', u_nonzero)
print('u_where =\n', u_where)
print('u_bool =\n', u_bool)

a:
 [[-1  0  0]
 [ 1  0 -2]
 [-1  2 -2]]
u_nonzero =
 [-1  1 -2 -1  2 -2]
u_where =
 [-1  1 -2 -1  2 -2]
u_bool =
 [-1  1 -2 -1  2 -2]


In [38]:
a = np.random.randint(-2, 3, size=(3, 3))
print('a:\n', a)

u_nonzero = a[np.nonzero(a > 0)]
u_where = a[np.where(a > 0)]
u_bool = a[a > 0]

print('u_nonzero =\n', u_nonzero)
print('u_where =\n', u_where)
print('u_bool =\n', u_bool)

a:
 [[-2  1  2]
 [ 2 -1  2]
 [ 2  1  1]]
u_nonzero =
 [1 2 2 2 2 1 1]
u_where =
 [1 2 2 2 2 1 1]
u_bool =
 [1 2 2 2 2 1 1]
