# 🔎 넘파이 ndarray 객체의 인덱싱과 슬라이싱

In [1]:
import numpy as np

## ✅ 1차원 배열
- 파이썬 리스트와 같이 반복문 사용이 가능하다.

### 인덱싱
파이썬 리스트 인덱싱 외에도 추가 기능을 제공한다.

In [2]:
a = np.arange(10)
print('a =', a)

print('a[0] =', a[0])
print('a[3] =', a[3])

print('a[-1] =', a[-1])
print('a[-3] =', a[-3])

a = [0 1 2 3 4 5 6 7 8 9]
a[0] = 0
a[3] = 3
a[-1] = 9
a[-3] = 7


In [3]:
# 추가 기능 1
a = np.arange(10)
indices = np.array([0, 3, 6, -1])
print('a =', a)

print('a[[0, 3, 6, -1]] =', a[[0, 3, 6, -1]])
print('a[indices] =', a[indices])
print('a[a % 3 == 0] =', a[a % 3 == 0])

a = [0 1 2 3 4 5 6 7 8 9]
a[[0, 3, 6, -1]] = [0 3 6 9]
a[indices] = [0 3 6 9]
a[a % 3 == 0] = [0 3 6 9]


In [4]:
# 추가 기능 2 (for문 대체) ⭐️⭐️⭐️⭐️⭐️
a = np.arange(1, 11)
print('a =', a)

a[:5] = 0
print('a =', a)

b = np.arange(1, 11)
print('b =', b)

b[::2] = 999
print('b =', b)

a = [ 1  2  3  4  5  6  7  8  9 10]
a = [ 0  0  0  0  0  6  7  8  9 10]
b = [ 1  2  3  4  5  6  7  8  9 10]
b = [999   2 999   4 999   6 999   8 999  10]


### 슬라이싱
- arr[x, y)

In [5]:
a =np.arange(10)
print('a =', a)

print('a[0:3] =', a[0:3])
print('a[5:-1] =', a[5:-1])
print('a[-2:] =', a[-2:])  # last 2 elements

print('a[::3] =', a[::3])
print('a[7:2:-1] =', a[7:2:-1])
print('a[::-1] =', a[::-1])

a = [0 1 2 3 4 5 6 7 8 9]
a[0:3] = [0 1 2]
a[5:-1] = [5 6 7 8]
a[-2:] = [8 9]
a[::3] = [0 3 6 9]
a[7:2:-1] = [7 6 5 4 3]
a[::-1] = [9 8 7 6 5 4 3 2 1 0]


## ✅ 2차원 배열
- 바깥쪽 차원(outer dimension)부터 접근한다.
- 서로 다른 차원은 콤마를 기준으로 인덱싱한다.

In [6]:
a = np.arange(12).reshape((3, 4))
print('a=\n', a)

print('a[0] =', a[0])
print('a[2] =', a[2])

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0] = [0 1 2 3]
a[2] = [ 8  9 10 11]


In [7]:
a = np.arange(9).reshape((3, 3))
print('a=\n', a)

print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
print(a[2, 0], a[2, 1], a[2, 2])

a=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
0 1 2
3 4 5
6 7 8


In [8]:
a = np.arange(12).reshape((4, 3))
print('a:\n', a)

print('a[0, 1:]=\n', a[0, 1:])
print('a[1:, 0]=\n', a[1:, 0])
print('a[:3, 1]=\n', a[:3, 1])
print('a[1:3, 2]=\n', a[1:3, 2])

a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a[0, 1:]=
 [1 2]
a[1:, 0]=
 [3 6 9]
a[:3, 1]=
 [1 4 7]
a[1:3, 2]=
 [5 8]


In [9]:
a = np.arange(16).reshape((4, 4))
print('a:\n', a)

print('a[1:3, 1:3]=\n', a[1:3, 1:3])
print('a[:2, :-1]=\n', a[:2, :-1])
print('a[1:, -2:]\n', a[1:, -2:])
print('a[-2:, :-2]\n', a[-2:, :-2])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a[1:3, 1:3]=
 [[ 5  6]
 [ 9 10]]
a[:2, :-1]=
 [[0 1 2]
 [4 5 6]]
a[1:, -2:]
 [[ 6  7]
 [10 11]
 [14 15]]
a[-2:, :-2]
 [[ 8  9]
 [12 13]]


In [10]:
a = np.arange(9).reshape((3, 3))
print('a:\n', a)

horizontal_flip = a[:, ::-1]
print('horizontal_flip:\n', horizontal_flip)

vertical_flip = a[::-1, :]
print('vertical_flip:\n', vertical_flip)

rotation180 = a[::-1, ::-1]
print('rotation180\n:', rotation180)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
horizontal_flip:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
vertical_flip:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
rotation180
: [[8 7 6]
 [5 4 3]
 [2 1 0]]


In [12]:
# ... 기호의 의미
a = np.arange(16).reshape((4, 4))
print('a:\n', a)

print('a[0, :]:\n', a[0, :])
print('a[0, ...]:\n', a[0, ...])

print('a[:, 1]:\n', a[:, 1])
print('a[..., 1]:\n', a[..., 1])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
a[0, :]:
 [0 1 2 3]
a[0, ...]:
 [0 1 2 3]
a[:, 1]:
 [ 1  5  9 13]
a[..., 1]:
 [ 1  5  9 13]
